Module 1:
oluwatobi-fasasi/my-portfolio-website pull request #14
Opened 2023-03-02 15:55 UTC by oluwatobi-fasasi

2023-03-02 15:58 UTC, oluwatobi-fasasi commented
- Finish desktop view

2023-03-02 17:18 UTC, DuaneDave requested changes
Hi @oluwatobi-fasasi 👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ README is professional and descriptive
✔️ PR summary is very descriptive
✔️ The codebase is well organized

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Ensuring that you use one account only when working on a project in order to not cause confusion for code reviewers.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 17:18 UTC, DuaneDave commented on index.html
>              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
Also, I noticed that the cards on the left of the about section are currently arranged in one column instead of two as seen in the Figma template. Kindly address this issue to make your version match Figma's

YOUR VERSION

![badCol](https://user-images.githubusercontent.com/84930355/222499096-b957449f-7d6c-4007-abad-ae3369c3c42f.PNG)


FIGMA DESIGN

![oneCol](https://user-images.githubusercontent.com/84930355/222499185-6e31011b-e891-4e4a-befb-81506c1a6e03.PNG)

2023-03-02 17:18 UTC, DuaneDave commented on index.html
>          </form>
The form is correctly implemented but the specified font on Figma is not being respected especially on the input fields and the text area. To make the UI much more pleasing, I recommend you address this issue.

![form](https://user-images.githubusercontent.com/84930355/222502284-bfabc795-3834-4745-a0fd-5809f76aa0b6.PNG)

2023-03-04 09:22 UTC, MeqdamAlqudah approved these changes
Hi @oluwatobi-fasasi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/74744787/222890289-02c24a63-6889-4512-9855-aa4f7e114f32.png)

## Highlights 
:+1: no linter errors 
:+1: design looks greate

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-04 09:25 UTC, merged

2023-04-14 12:07 UTC, oluwatobi-fasasi commented
Thanks @MeqdamAlqudah, @DuaneDave, all suggestion changes are fully implemented