Module 1: Portfolio
oluwatobi-fasasi/my-portfolio-website pull request #4
Opened 2023-02-16 15:38 UTC by oluwatobi-fasasi

Add works section
Add about section

2023-02-16 17:41 UTC, Ibizugbe requested changes
Hi @Fasasi 👋👋, 

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f69656d6d596a3332456945655a59766a70712f67697068792e676966](https://user-images.githubusercontent.com/64643995/219433460-ba556a2c-0fab-403e-8eca-8c09b2276b5b.gif)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅

- [ ] Linters are passing✅
- [ ] Github flow has been used✅


## Required Changes ♻️

- [ ] As specified in the previous milestone of the project, the mobile screen size should be from `375px` this is affecting the responsiveness of your project😉 I suggest you kindly fix it🤗

Your code
<img width="400" alt="375px width" src="https://user-images.githubusercontent.com/64643995/219434535-41d3f4f6-2ca9-4825-b837-ede442ed05b0.png">

appearance
<img width="296" alt="inresponsive" src="https://user-images.githubusercontent.com/64643995/219434615-3bf81f0c-0fd7-4460-ae0f-98cfe7e94925.png">

kindly adjust the width😉

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Kindly ensure the contents of your page are wrapped in a `main` tag as this makes your page more semantic😉 The previous reviewers may have forgotten to point it, but it is a requirement🤗🤗

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 17:41 UTC, Ibizugbe commented on index.html
> +            <section class="works">
Nice work so far👍 but currently, there is a part of the design missing😉 kindly take note of the highlighted part in the image😉 don't forget, It is a requirement that we stick to the design in this milestone🤗🤗

<img width="221" alt="absent_section1" src="https://user-images.githubusercontent.com/64643995/219440490-b3ec372d-f0f6-4002-b74a-97c4cb46d34c.png">

kindly add that part of the design to your project🤗🤗

2023-02-16 17:41 UTC, Ibizugbe commented on index.html
> +        </section>
Nice work building the `b=about`  section😉 but there our still some things making our project different from the given design😉😉

Your about
<img width="148" alt="your__Special image" src="https://user-images.githubusercontent.com/64643995/219444510-7d6a7661-89b1-49d3-b644-f5ffc448000e.png">



Design
<img width="76" alt="design__specual images" src="https://user-images.githubusercontent.com/64643995/219444392-88fac7cf-e2cb-437c-b6b0-519c0057209e.png">

kindly see the images absent, and notice the difference in spacings and fix the issue🤗

2023-02-17 09:37 UTC, oluwatobi-fasasi commented
Hello,

The images on my about page are not showing. I downloaded the PNG file on
my local system but it is not showing up on my work.

That is why I ignored it earlier.

Thank you
ᐧ
ᐧ

On Thu, Feb 16, 2023 at 6:41 PM Abraham Ibizugbe ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Fasasi <https://github.com/Fasasi> 👋👋,
>
> [image:
> 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f69656d6d596a3332456945655a59766a70712f67697068792e676966]
> <https://user-images.githubusercontent.com/64643995/219433460-ba556a2c-0fab-403e-8eca-8c09b2276b5b.gif>
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights✅
>
>    - Linters are passing✅
>    - Github flow has been used✅
>
> Required Changes ♻️
>
>    - As specified in the previous milestone of the project, the mobile
>    screen size should be from 375px this is affecting the responsiveness
>    of your project😉 I suggest you kindly fix it🤗
>
> Your code
> [image: 375px width]
> <https://user-images.githubusercontent.com/64643995/219434535-41d3f4f6-2ca9-4825-b837-ede442ed05b0.png>
>
> appearance
> [image: inresponsive]
> <https://user-images.githubusercontent.com/64643995/219434615-3bf81f0c-0fd7-4460-ae0f-98cfe7e94925.png>
>
> kindly adjust the width😉
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
>    - [OPTIONAL] Kindly ensure the contents of your page are wrapped in a
>    main tag as this makes your page more semantic😉 The previous
>    reviewers may have forgotten to point it, but it is a requirement🤗🤗
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In styles.css
> <https://github.com/oluwatobi-fasasi/my-portfolio-website/pull/4#discussion_r1108748065>
> :
>
> > +/* .rectangle {
>
> +  background-color: rgb(119, 84, 84);
>
> +  width: 320px;
>
> +  height: 160px;
>
> +  margin-top: 30px;
>
> +} */
>
>
> I suggest you take away every block of commented code as it is not a good
> coding practice since it makes your code looks scattered😉
> ------------------------------
>
> In index.html
> <https://github.com/oluwatobi-fasasi/my-portfolio-website/pull/4#discussion_r1108798492>
> :
>
> > +        <section class="project">
>
> +            <!-- <div class="rectangle"></div> -->
>
> +            <h2>Projects</h2>
>
> +            <section class="works">
>
>
> Nice work so far👍 but currently, there is a part of the design missing😉
> kindly take note of the highlighted part in the image😉 don't forget, It
> is a requirement that we stick to the design in this milestone🤗🤗
>
> [image: absent_section1]
> <https://user-images.githubusercontent.com/64643995/219440490-b3ec372d-f0f6-4002-b74a-97c4cb46d34c.png>
>
> kindly add that part of the design to your project🤗🤗
> ------------------------------
>
> In index.html
> <https://github.com/oluwatobi-fasasi/my-portfolio-website/pull/4#discussion_r1108817350>
> :
>
> > +        <section class="about-page">
>
> +            <div>
>
> +                <h2>About</h2>
>
> +                <p class="about-me">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ea eiusmod</p>
>
> +                <a href="https://microverse.org" class="cv-link">Get my CV <img src="images/ic_download.svg" alt="cv" class="cv-arrow"></a>
>
> +            </div>
>
> +            <div class="lang">
>
> +                <p>Languages</p>
>
> +                <ul>
>
> +                    <li>JavaScript(ES5/ES6)</li>
>
> +                    <li>Ruby</li>
>
> +                    <li>HTML</li>
>
> +                    <li>CSS</li>
>
> +                </ul>
>
> +            </div>
>
> +            <div class="framework">
>
> +                <p>Frameworks</p>
>
> +                <ul>
>
> +                    <li>Bootstrap</li>
>
> +                    <li>Ruby on rails</li>
>
> +                    <li>RSpec</li>
>
> +                    <li>Capibara</li>
>
> +                    <li>Selenium</li>
>
> +                </ul>
>
> +            </div>
>
> +            <div class="skills">
>
> +                <p>Skills</p>
>
> +                <ul>
>
> +                    <li>Codekit</li>
>
> +                    <li>Codepen</li>
>
> +                    <li>GitHub</li>
>
> +                    <li>GitLab</li>
>
> +                    <li>Terminal</li>
>
> +                </ul>
>
> +            </div>
>
> +        </section>
>
>
> Nice work building the b=about section😉 but there our still some things
> making our project different from the given design😉😉
>
> Your about
> [image: your__Special image]
> <https://user-images.githubusercontent.com/64643995/219444510-7d6a7661-89b1-49d3-b644-f5ffc448000e.png>
>
> Design
> [image: design__specual images]
> <https://user-images.githubusercontent.com/64643995/219444392-88fac7cf-e2cb-437c-b6b0-519c0057209e.png>
>
> kindly see the images absent, and notice the difference in spacings and
> fix the issue🤗
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/oluwatobi-fasasi/my-portfolio-website/pull/4#pullrequestreview-1301872320>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZONL637OUMKSSYSCOMN2UTWXZRFPANCNFSM6AAAAAAU6KTNKE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-02-17 10:34 UTC, oluwatobi-fasasi commented
Thanks, I just found my way around it.
ᐧ

On Fri, Feb 17, 2023 at 10:37 AM Abdulwasiu Fasasi ***@***.***>
wrote:

> Hello,
>
> The images on my about page are not showing. I downloaded the PNG file on
> my local system but it is not showing up on my work.
>
> That is why I ignored it earlier.
>
> Thank you
> ᐧ
> ᐧ
>
> On Thu, Feb 16, 2023 at 6:41 PM Abraham Ibizugbe ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hi @Fasasi <https://github.com/Fasasi> 👋👋,
>>
>> [image:
>> 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f69656d6d596a3332456945655a59766a70712f67697068792e676966]
>> <https://user-images.githubusercontent.com/64643995/219433460-ba556a2c-0fab-403e-8eca-8c09b2276b5b.gif>
>>
>> Good job so far!
>> There are some issues that you still need to work on to go to the next
>> project but you are almost there!
>> Highlights✅
>>
>>    - Linters are passing✅
>>    - Github flow has been used✅
>>
>> Required Changes ♻️
>>
>>    - As specified in the previous milestone of the project, the mobile
>>    screen size should be from 375px this is affecting the responsiveness
>>    of your project😉 I suggest you kindly fix it🤗
>>
>> Your code
>> [image: 375px width]
>> <https://user-images.githubusercontent.com/64643995/219434535-41d3f4f6-2ca9-4825-b837-ede442ed05b0.png>
>>
>> appearance
>> [image: inresponsive]
>> <https://user-images.githubusercontent.com/64643995/219434615-3bf81f0c-0fd7-4460-ae0f-98cfe7e94925.png>
>>
>> kindly adjust the width😉
>>
>> *Check the comments under the review.*
>> Optional suggestions
>>
>> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
>> the approval of this PR. However, I strongly recommend you to take them
>> into account as they can make your code better.*
>>
>> You can also consider:
>>
>>    - [OPTIONAL] Kindly ensure the contents of your page are wrapped in a
>>    main tag as this makes your page more semantic😉 The previous
>>    reviewers may have forgotten to point it, but it is a requirement🤗🤗
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>> ------------------------------
>>
>> In styles.css
>> <https://github.com/oluwatobi-fasasi/my-portfolio-website/pull/4#discussion_r1108748065>
>> :
>>
>> > +/* .rectangle {
>>
>> +  background-color: rgb(119, 84, 84);
>>
>> +  width: 320px;
>>
>> +  height: 160px;
>>
>> +  margin-top: 30px;
>>
>> +} */
>>
>>
>> I suggest you take away every block of commented code as it is not a good
>> coding practice since it makes your code looks scattered😉
>> ------------------------------
>>
>> In index.html
>> <https://github.com/oluwatobi-fasasi/my-portfolio-website/pull/4#discussion_r1108798492>
>> :
>>
>> > +        <section class="project">
>>
>> +            <!-- <div class="rectangle"></div> -->
>>
>> +            <h2>Projects</h2>
>>
>> +            <section class="works">
>>
>>
>> Nice work so far👍 but currently, there is a part of the design missing😉
>> kindly take note of the highlighted part in the image😉 don't forget, It
>> is a requirement that we stick to the design in this milestone🤗🤗
>>
>> [image: absent_section1]
>> <https://user-images.githubusercontent.com/64643995/219440490-b3ec372d-f0f6-4002-b74a-97c4cb46d34c.png>
>>
>> kindly add that part of the design to your project🤗🤗
>> ------------------------------
>>
>> In index.html
>> <https://github.com/oluwatobi-fasasi/my-portfolio-website/pull/4#discussion_r1108817350>
>> :
>>
>> > +        <section class="about-page">
>>
>> +            <div>
>>
>> +                <h2>About</h2>
>>
>> +                <p class="about-me">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ea eiusmod</p>
>>
>> +                <a href="https://microverse.org" class="cv-link">Get my CV <img src="images/ic_download.svg" alt="cv" class="cv-arrow"></a>
>>
>> +            </div>
>>
>> +            <div class="lang">
>>
>> +                <p>Languages</p>
>>
>> +                <ul>
>>
>> +                    <li>JavaScript(ES5/ES6)</li>
>>
>> +                    <li>Ruby</li>
>>
>> +                    <li>HTML</li>
>>
>> +                    <li>CSS</li>
>>
>> +                </ul>
>>
>> +            </div>
>>
>> +            <div class="framework">
>>
>> +                <p>Frameworks</p>
>>
>> +                <ul>
>>
>> +                    <li>Bootstrap</li>
>>
>> +                    <li>Ruby on rails</li>
>>
>> +                    <li>RSpec</li>
>>
>> +                    <li>Capibara</li>
>>
>> +                    <li>Selenium</li>
>>
>> +                </ul>
>>
>> +            </div>
>>
>> +            <div class="skills">
>>
>> +                <p>Skills</p>
>>
>> +                <ul>
>>
>> +                    <li>Codekit</li>
>>
>> +                    <li>Codepen</li>
>>
>> +                    <li>GitHub</li>
>>
>> +                    <li>GitLab</li>
>>
>> +                    <li>Terminal</li>
>>
>> +                </ul>
>>
>> +            </div>
>>
>> +        </section>
>>
>>
>> Nice work building the b=about section😉 but there our still some things
>> making our project different from the given design😉😉
>>
>> Your about
>> [image: your__Special image]
>> <https://user-images.githubusercontent.com/64643995/219444510-7d6a7661-89b1-49d3-b644-f5ffc448000e.png>
>>
>> Design
>> [image: design__specual images]
>> <https://user-images.githubusercontent.com/64643995/219444392-88fac7cf-e2cb-437c-b6b0-519c0057209e.png>
>>
>> kindly see the images absent, and notice the difference in spacings and
>> fix the issue🤗
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/oluwatobi-fasasi/my-portfolio-website/pull/4#pullrequestreview-1301872320>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZONL637OUMKSSYSCOMN2UTWXZRFPANCNFSM6AAAAAAU6KTNKE>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***
>> com>
>>
>

2023-02-17 12:10 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @oluwatobi-fasasi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 12:10 UTC, bobb-Rob commented on index.html
>          </header>
- [ ] [OPTIONAL] The hamburger/menu icon is touching the right edge of the screen. Please fix this.
![image](https://user-images.githubusercontent.com/84156714/219650183-ca9d0eda-5d0f-4af8-b08c-a397ea1aa39a.png)

2023-02-17 14:17 UTC, merged

2023-04-14 11:57 UTC, oluwatobi-fasasi commented on styles.css
> +} */
Thanks @Ibizugbe, all suggestion changes are fully implemented

2023-04-14 12:01 UTC, oluwatobi-fasasi commented on index.html
>          </header>
Thanks @bobb-Rob, all suggestion changes are fully implemented