Portfolio
oluwatobi-fasasi/my-portfolio-website pull request #6
Opened 2023-02-22 11:17 UTC by oluwatobi-fasasi

- Add contact form
- Add footer

2023-02-22 14:41 UTC, zieeco requested changes
Hi @Team,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 14:41 UTC, zieeco commented on index.html
> +            <a href="https://microverse.org" class="button">Start collaboration</a>
- Hey, this should be a button as you want to make users able to submit your form if they want to get in touch with you. the button `type="submit"` however, you can choose not to specify it because a button in a form by default would be submitted to the form. Please, let's fix this little issue.

2023-02-22 14:41 UTC, zieeco commented on styles.css
> +}
- Hey, please, let's improve on our styles by using flexbox to lay out the content of this section to make your design layout well compared to the original design. see the design below:


*original design*
![Screenshot from 2023-02-22 15-28-49](https://user-images.githubusercontent.com/59397159/220655357-80d3f3d3-3ab8-4cf4-af39-1a43939a26f9.png)

*your design*
![Screenshot from 2023-02-22 15-25-10](https://user-images.githubusercontent.com/59397159/220655366-18aac4c8-35ee-4894-89a9-71f834ce5537.png)

2023-02-22 18:18 UTC, frank1738 reviewed
Hi @oluwatobi-fasasi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project with no linter checks running. Kindly ensure linter checks are running and also solve the conflict between your branches

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-22 18:28 UTC, shella12 requested changes
Hi @oluwatobi-fasasi , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights

- All linters passed ✅ 
- Correct use of git flow ✅ 

 ## Required Changes ♻️

- [ ] _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 18:28 UTC, shella12 commented on index.html
> +                <button type="button">Start collaboration</button>
- [ ] Great job 👍 adding the formspree for contact submission but as mention by the previous reviewer please use `type = "submit"` for `start collaboration` button instead of `type = "button"`. The ⚠️ contact form is not submitting to the formspree ⚠️ 🚨  because the button type is not `submit` and upon clicking it, it's not performing any action. Please 🙏 make sure that the submit `button` is either an `input element` with` type submit `or a `button` ⏺️  element with `type submit` or with no type attribute (note that it defaults to a submit type when no type attribute is used.) because it is used to submit all the user values to the form handler. The Form Handler is a server page that activates a script for processing all the input values (in your case farmspree).


- [ ] [OPTIONAL] Great job add button interaction as per requirements but Please make sure to add them according to the Fogma design template

**_Figma template_**

<img width="291" alt="Screenshot 2023-02-22 at 11 19 29 PM" src="https://user-images.githubusercontent.com/44798044/220721903-6c58361c-dbaa-442f-9a1d-40954eeeb6fb.png">

**_Your Implementaions_**

https://user-images.githubusercontent.com/44798044/220721842-90684359-4820-4080-9dc7-bad36cdfea46.mov

2023-02-22 18:28 UTC, shella12 commented on index.html
> +                    type="email"
- [ ] As mentioned by the previous reviewer please make sure that 
       - [ ]  you use `flexbox` to style the contact us section as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#project-requirements) of the project

>  In order to lay out the elements on the page you should use Flexbox.

       - [ ] Also ☺️  to fix the margin from the left of the screen to make it look as close to the [figam design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9&t=ZuNU1PLWYc0RtI2T-0) as possible, as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#project-requirements) of the project

> You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9&t=ZuNU1PLWYc0RtI2T-0).
Implement the button interactions (enable, hover, etc.).

_**Figma design**_ 

<img width="259" alt="Screenshot 2023-02-22 at 11 20 46 PM" src="https://user-images.githubusercontent.com/44798044/220720803-ea1a2fb4-b176-4c00-9ebf-f052522071cc.png">

_**Your design**_

<img width="353" alt="Screenshot 2023-02-22 at 11 10 39 PM" src="https://user-images.githubusercontent.com/44798044/220721060-7f8ec3ea-a9d5-4ba9-8ba7-c170b99b4e39.png">

2023-02-23 17:39 UTC, ouasamine approved these changes
Hi @Fasasi  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You have done a good job implementing the requested changes 👏🏽 
- Nice work on the UI generally ✔️ 

## Optional suggestions

- [ ] [OPTIONAL] Your design looks very good and matches the Figma design except for the responsiveness part, currently, your design is not shown properly on +375px screens and that is because you set the width to `width: 375px;` in you `main` style instead of giving it a responsive value like `width: 100%;`, please try to address this issue, and remember that having nice looking projects on your GitHub increase the chances of being contacted by a hiring manager.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 18:56 UTC, merged

2023-04-14 12:02 UTC, oluwatobi-fasasi commented on styles.css
> +}
Thanks @zieeco, all suggestion changes are fully implemented

2023-04-14 12:05 UTC, oluwatobi-fasasi commented
Thanks @ouasamine, @frank1738, all suggestion changes are fully implemented